### ISSUE TITLE
Use with await? Or backpressure? Need to slow down "message" event so I can process them

### ISSUE THREAD

**Issue by GeoffreyPlitt** [robertklep/node-mbox#10]
I'm unable to slow down the "message" event so that it can wait for processing to happen. The examples shown don't seem to pass a "done()" to the "message" event handler for async coordination.

So if my message processing needs a moment, the messages build up and I need to either drop them or store them in memory. I'm operating on a large 40GB mbox file.

Please advise

**Comment by robertklep** [comment]
It might be possible to implement pause/resume, but perhaps a quicker solution would be to split the parsing and the processing with some sort of persistent job queue ([`level-jobs`](https://github.com/pgte/level-jobs), [`micro-queue`](https://github.com/saintedlama/microq)).

**Comment by GeoffreyPlitt** [comment]
The writes to mongo would still be slower than the events coming from this parser, so memory would start to leak. Gonna try writing my own with a generator.
