### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by maksimlya** [robertklep/node-mbox#12]
Hi, the current implementation of splitting the mbox file into emls is looking for line that starts with 'From ' . I had eml's that in their text had lines that started with 'From ', and had nothing to do with mbox splitter. That caused bugs - broken messages. You need to check more values in that line, for example that it ends with a date. Provided mbox file with example to the issue.
[test.mbox.zip](https://github.com/robertklep/node-mbox/files/10815188/test.mbox.zip)

**Comment by robertklep** [comment]
Officially, lines in the e-mail body that start with "From " should be "From-quoted", as documented [here](http://qmail.org./man/man5/mbox.html).

This module doesn't support any other mbox formats.

**Comment by maksimlya** [comment]
I assume that our export should process each eml and replace the text in body that starts with 'From '. We did see some clients tho that can handle our output, while others cannot. (Thunderbird does not handles it well while apple mail does it just fine.) Can close it as the issue is very specific anyway.
