### ISSUE TITLE
Any file return one message

### ISSUE THREAD

**Issue by misteral** [robertklep/node-mbox#5]
```
var mbox    = new Mbox('blackbox.psd');
mbox.on('message', function(msg) {
  console.log('got a message', msg);
});
```
any file return 1 message, aslo if it not have text 'From'

msg = ' From ' + content of blackbox.psd

**Comment by robertklep** [comment]
Easy solution: only feed it mbox files 😉

But I get your point. The issue is that even if a file starts with `From `, it doesn't necessarily have to be an mbox file anyway. So I _could_ have it check for that header, but perhaps it should just assume that anything that gets passed through it is a valid mbox file (like it does now).

**Comment by misteral** [comment]
Hi, but blackbox.psd not have 'From' string in fact. How i can check what the file is have mbox format? I think if mbox-npm return 0 messages - is not a mbox file.

**Comment by robertklep** [comment]
Strictly speaking, node-mbox is meant to parse mbox files, not to check if a file is a valid mbox file. I'll add a "strict" mode that you can enable which will cause an error to be thrown when the input doesn't start with `From`, does that sound reasonable?

— robert (iPad)

**Comment by robertklep** [comment]
@misteral I pushed an update, if you care to test it:
```
npm i robertklep/node-mbox#b636c4c
```

The two main changes:
* it should return a message count of 0 for non-mbox files (however, strictly speaking, if it finds the string `\nFrom ` _anywhere_ in the file, it may still think it found a message);
* there's an option [`strict`](https://github.com/robertklep/node-mbox/tree/b636c4cc0780245f74aa783847a62a1ad4fe3026#options) that will cause an error event to be thrown if the input doesn't start with `From `;

If it works as expected, I'll publish it as `v0.3.0`.

**Comment by misteral** [comment]
Yes, it works! Thanks. Please release v0.3.0

**Comment by robertklep** [comment]
Done!
