### ISSUE TITLE
stream.on is not a function error

### ISSUE THREAD

**Issue by stokaace** [robertklep/node-mbox#9]
The streaming example given in the documentation doesn't seem to work/ throws a "stream.on is not a function" error.  What am I missing here?

`const mbox = new Mbox({ streaming : true });

// `message` event emits stream
mbox.on('message', function(stream) {
  stream.on('data', function(chunk) {
    ...
  }).on('end', function() {
    ...
  });
});

process.stdin.pipe(mbox);`

**Comment by robertklep** [comment]
My bad! The option is called `stream`, not `streaming`:

```
const mbox = new Mbox({ stream : true });
...
```

**Comment by stokaace** [comment]
That's it.  Thank you for the fast response!
